Repository bcgov/fas-ui, pull requests merged in 2021-07, with the labels that each got.

#6 Staff logins into the new Fee Accounting System#7791
  .gitignore
  jest.config.js
  jest.setup.ts
  src/assets/scss/layout.scss
  src/components/Dashboard/Dashboard.vue
  src/components/Dashboard/Search.vue
  src/components/Dashboard/index.ts
  src/composables/Dashboard/index.ts
  src/composables/Dashboard/useSearch.ts
  src/router/routes.ts
  src/views/About.vue
  src/views/Dashboard.vue
Labels: enhancement

#7 Feature/7791 1
  .eslintrc.js
  jest.config.js
  jest.setup.ts
  package-lock.json
  package.json
  src/components/Dashboard/Dashboard.vue
  src/components/Dashboard/Search.vue
  src/components/HelloWorld.vue
  src/components/common/DateRangeFilter.vue
  src/components/common/InterimLanding.vue
  src/composables/Dashboard/index.ts
  src/composables/Dashboard/useSearch.ts
  src/composables/common/index.ts
  src/composables/common/useDateRange.ts
  src/composables/common/useNavigation.ts
  src/locales/en.json
  src/locales/fr.json
  src/main.ts
  src/plugins/i18n.ts
  src/router/routes.ts
  src/service-worker.js
  src/util/common-util.ts
  src/util/constants.ts
  src/views/Home.vue
  src/views/PageNotFound.vue
  tests/unit/components/Dashboard/dashboard.spec.ts
  tests/unit/components/Dashboard/search.spec.ts
  tests/unit/example.spec.ts
  tests/unit/views/app.spec.ts
  tests/unit/views/auth/signinView.spec.ts
  tests/unit/views/auth/signoutView.spec.ts
  tests/unit/views/dashboard.spec.ts
  tests/unit/views/pageNotFound.spec.ts
  tsconfig.json
Labels: enhancement

#8 Staff creates a Routing Slip | date picker
  .eslintrc.js
  package-lock.json
  package.json
  src/components/Dashboard/Search.vue
  src/components/common/DatePicker.vue
  src/composables/Dashboard/useSearch.ts
  src/composables/common/index.ts
  src/composables/common/useDatePicker.ts
  tsconfig.json
Labels: enhancement

#9 Feature/7792 WIP
  public/img/icons/android-chrome-192x192.png
  public/img/icons/android-chrome-512x512.png
  public/img/icons/android-chrome-maskable-192x192.png
  public/img/icons/android-chrome-maskable-512x512.png
  public/img/icons/apple-touch-icon-120x120.png
  public/img/icons/apple-touch-icon-152x152.png
  public/img/icons/apple-touch-icon-180x180.png
  public/img/icons/apple-touch-icon-60x60.png
  public/img/icons/apple-touch-icon-76x76.png
  public/img/icons/apple-touch-icon.png
  public/img/icons/favicon-16x16.png
  public/img/icons/favicon-32x32.png
  public/img/icons/msapplication-icon-144x144.png
  public/img/icons/mstile-150x150.png
  public/img/icons/safari-pinned-tab.svg
  public/index.html
  src/components/RoutingSlip/CreateRoutingSlip.vue
  src/components/RoutingSlip/CreateRoutingSlipCashPayment.vue
  src/components/RoutingSlip/CreateRoutingSlipChequePayment.vue
  src/components/RoutingSlip/CreateRoutingSlipDetails.vue
  src/components/RoutingSlip/CreateRoutingSlipPayment.vue
  src/components/RoutingSlip/index.ts
  src/composables/RoutingSlip/useCreateRoutingSlip.ts
  src/composables/RoutingSlip/useCreateRoutingSlipCashPayment.ts
  src/composables/RoutingSlip/useCreateRoutingSlipChequePayment.ts
  src/composables/RoutingSlip/useCreateRoutingSlipDetails.ts
  src/composables/RoutingSlip/useCreateRoutingSlipPayment.ts
  src/main.ts
  src/models/Payment.ts
  src/models/RoutingSlip.ts
  src/plugins/i18n.ts
  src/router/routes.ts
  src/util/common-util.ts
  src/util/constants.ts
  src/views/CreateRoutingSlipView.vue
  src/views/UnauthorizedView.vue
Labels: WIP, enhancement

#10 Changes for keycloak config and to auto-authenticate user
  package.json
  public/config/kc/keycloak.json
  src/main.ts
  src/util/common-util.ts
Labels: enhancement

#11 Staff creates a Routing Slip#7792
  jest.config.js
  package-lock.json
  src/components/Dashboard/Dashboard.vue
  src/components/RoutingSlip/CreateRoutingSlip.vue
  src/components/RoutingSlip/CreateRoutingSlipDetails.vue
  src/components/common/DatePicker.vue
  src/composables/RoutingSlip/useCreateRoutingSlip.ts
  src/composables/RoutingSlip/useCreateRoutingSlipDetails.ts
  src/services/routingSlip.services.ts
  src/store/index.ts
  src/store/modules/routingSlip.ts
  src/util/config-helper.ts
  src/util/http-util.ts
  src/views/UnauthorizedView.vue
  tests/unit/components/common/datePicker.spec.ts
  tsconfig.json
Labels: enhancement

#13 Staff creates a Routing Slip#7792
  src/components/RoutingSlip/CreateRoutingSlip.vue
  src/components/RoutingSlip/CreateRoutingSlipCashPayment.vue
  src/components/RoutingSlip/CreateRoutingSlipChequePayment.vue
  src/composables/RoutingSlip/useCreateRoutingSlip.ts
  src/composables/RoutingSlip/useCreateRoutingSlipCashPayment.ts
  src/composables/RoutingSlip/useCreateRoutingSlipChequePayment.ts
  src/composables/RoutingSlip/useCreateRoutingSlipDetails.ts
  src/composables/RoutingSlip/useCreateRoutingSlipPayment.ts
  src/store/modules/routingSlip.ts
Labels: WIP

#12 Feature/7792- Modal Dialog
  package-lock.json
  src/components/RoutingSlip/CreateRoutingSlip.vue
  src/components/RoutingSlip/CreateRoutingSlipCashPayment.vue
  src/components/RoutingSlip/CreateRoutingSlipChequePayment.vue
  src/components/RoutingSlip/CreateRoutingSlipPayment.vue
  src/components/common/ModalDialog.vue
  src/composables/RoutingSlip/useCreateRoutingSlip.ts
  src/composables/RoutingSlip/useCreateRoutingSlipCashPayment.ts
  src/composables/RoutingSlip/useCreateRoutingSlipDetails.ts
  src/composables/RoutingSlip/useCreateRoutingSlipPayment.ts
  src/composables/common/index.ts
  src/composables/common/useModalDialog.ts
  src/locales/en.json
  src/store/modules/routingSlip.ts
Labels: WIP, enhancement

#14 7792 backend integration
  src/components/RoutingSlip/CreateRoutingSlip.vue
  src/components/RoutingSlip/CreateRoutingSlipCashPayment.vue
  src/components/RoutingSlip/CreateRoutingSlipChequePayment.vue
  src/components/RoutingSlip/CreateRoutingSlipDetails.vue
  src/composables/RoutingSlip/useCreateRoutingSlip.ts
  src/composables/RoutingSlip/useCreateRoutingSlipCashPayment.ts
  src/composables/RoutingSlip/useCreateRoutingSlipChequePayment.ts
  src/composables/RoutingSlip/useCreateRoutingSlipDetails.ts
  src/composables/RoutingSlip/useCreateRoutingSlipPayment.ts
  src/models/Payment.ts
  src/models/RoutingSlip.ts
  src/services/routingSlip.services.ts
  src/store/modules/routingSlip.ts
Labels: WIP, enhancement

#15 Staff creates a Routing Slip#7792 | modal
  src/components/RoutingSlip/CreateRoutingSlip.vue
  src/components/RoutingSlip/CreateRoutingSlipDetails.vue
  src/components/RoutingSlip/CreateRoutingSlipPayment.vue
  src/components/common/ModalDialog.vue
Labels: WIP

#19 package lock
  .gitignore
  package-lock.json
Labels: WIP

#21 Staff creates a Routing Slip#7792 | test cases
  src/components/RoutingSlip/CreateRoutingSlipChequePayment.vue
  src/store/modules/routingSlip.ts
  tests/unit/components/RoutingSlip/CreateRoutingSlipChequePayment.spec.ts
Labels: WIP

#22 Feature/7792 tests
  src/components/RoutingSlip/CreateRoutingSlip.vue
  src/components/RoutingSlip/CreateRoutingSlipDetails.vue
  src/components/RoutingSlip/CreateRoutingSlipPayment.vue
  tests/unit/components/RoutingSlip/createRoutingSlipPayment.spec.ts
  tests/unit/components/routingSlip/createRoutingSlip.spec.ts
  tests/unit/components/routingSlip/createRoutingSlipDetails.spec.ts
  tests/unit/views/createRoutingSlip.spec.ts
Labels: enhancement

#25 7792 - progress circle
  src/components/RoutingSlip/CreateRoutingSlip.vue
  src/composables/RoutingSlip/useCreateRoutingSlip.ts
Labels: enhancement

#26 Edit a routing slip#7795
  src/components/ViewRoutingSlip/PrintRoutingSlip.vue
  src/components/ViewRoutingSlip/RoutingSlipInfo.vue
  src/components/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/useViewRoutingSlip.ts
  src/router/routes.ts
  src/services/routingSlip.services.ts
  src/store/modules/routingSlip.ts
  src/views/ViewRoutingSlip.vue
Labels: WIP

#28 Adding auth guard for routes and unauthorized view
  src/locales/en.json
  src/router/index.ts
  src/router/routes.ts
  src/util/constants.ts
  src/views/Unauthorized.vue
  tests/unit/views/unauthorized.spec.ts
Labels: enhancement

#29 8234 - Payment Information
  src/components/RoutingSlip/CreateRoutingSlipCashPayment.vue
  src/components/RoutingSlip/CreateRoutingSlipChequePayment.vue
  src/components/ViewRoutingSlip/PaymentInformation.vue
  src/components/ViewRoutingSlip/index.ts
  src/composables/RoutingSlip/useCreateRoutingSlipChequePayment.ts
  src/composables/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/usePaymentInformation.ts
  src/views/ViewRoutingSlip.vue
  tests/unit/components/ViewRoutingSlip/paymentInformation.spec.ts
Labels: enhancement

#31 can directive implementation
  src/components/ViewRoutingSlip/PaymentInformation.vue
  src/components/ViewRoutingSlip/RoutingSlipTransaction.vue
  src/components/ViewRoutingSlip/index.ts
  src/directives/can.ts
  src/main.ts
  src/views/ViewRoutingSlip.vue
Labels: enhancement

#30 Feature/7795 1
  src/assets/scss/overrides.scss
  src/components/ViewRoutingSlip/RoutingSlipInfo.vue
  src/components/common/StatusList.vue
  src/composables/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/useRoutingSlipInfo.ts
  src/composables/ViewRoutingSlip/useViewRoutingSlip.ts
  src/composables/common/index.ts
  src/composables/common/useStatusList.ts
  src/models/Code.ts
  src/services/codes.service.ts
  src/services/routingSlip.services.ts
  src/store/index.ts
  src/store/modules/codes.ts
  src/store/modules/routingSlip.ts
  src/util/common-util.ts
  src/util/constants.ts
  tests/unit/components/ViewRoutingSlip/RoutingSlipInfo.spec.ts
  tests/unit/components/common/StatusList.spec.ts
  tests/unit/components/routingSlip/createRoutingSlip.spec.ts
  tests/unit/test-data/mock-code.ts
  tests/unit/test-data/mock-routing-slip.ts
  tests/unit/views/ViewRoutingSlip.spec.ts
Labels: enhancement

#33 View: Payment Information for a Routing Slip styles
  src/components/ViewRoutingSlip/PaymentInformation.vue
  src/components/ViewRoutingSlip/RoutingSlipInfo.vue
  src/composables/RoutingSlip/useCreateRoutingSlip.ts
  src/views/ViewRoutingSlip.vue
Labels: enhancement

#32 Feature/8235
  src/components/RoutingSlip/CreateRoutingSlipChequePayment.vue
  src/components/ViewRoutingSlip/PaymentInformation.vue
  src/components/ViewRoutingSlip/RoutingSlipTransaction.vue
  src/components/ViewRoutingSlip/TransactionDataTable.vue
  src/components/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/usePaymentInformation.ts
  src/composables/ViewRoutingSlip/useRoutingSlipTransaction.ts
  src/composables/ViewRoutingSlip/useTransactionDataTable.ts
  src/models/Invoice.ts
  src/models/RoutingSlip.ts
  src/store/modules/routingSlip.ts
  src/util/common-util.ts
  src/util/constants.ts
  tests/unit/components/ViewRoutingSlip/routingSlipTransaction.spec.ts
  tests/unit/components/ViewRoutingSlip/transactionDataTable.spec.ts
  tests/unit/test-data/mock-routing-slip.ts
Labels: enhancement

#34 8235 - UI spacing fix
  src/components/ViewRoutingSlip/RoutingSlipInfo.vue
  src/components/ViewRoutingSlip/RoutingSlipTransaction.vue
  src/components/ViewRoutingSlip/TransactionDataTable.vue
  src/composables/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/useRoutingSlipTransaction.ts
Labels: enhancement

#35 Feature/8235_resetstore
  src/components/Dashboard/Dashboard.vue
  src/components/ViewRoutingSlip/TransactionDataTable.vue
  src/composables/Dashboard/index.ts
  src/composables/Dashboard/useDashboard.ts
  src/composables/RoutingSlip/useCreateRoutingSlip.ts
  src/store/modules/routingSlip.ts
Labels: enhancement

#36 FAS UI display changes
  src/components/RoutingSlip/CreateRoutingSlipCashPayment.vue
  src/components/RoutingSlip/CreateRoutingSlipChequePayment.vue
  src/components/ViewRoutingSlip/RoutingSlipInfo.vue
Labels: enhancement

#37 fix amount view | for demo changes
  src/components/ViewRoutingSlip/PaymentInformation.vue
  src/components/ViewRoutingSlip/RoutingSlipInfo.vue
  src/components/ViewRoutingSlip/TransactionDataTable.vue
  src/composables/ViewRoutingSlip/usePaymentInformation.ts
  src/composables/ViewRoutingSlip/useTransactionDataTable.ts
  tests/unit/components/ViewRoutingSlip/paymentInformation.spec.ts
  tests/unit/components/ViewRoutingSlip/transactionDataTable.spec.ts
Labels: bug

#38 User groups for FAS#8116 | create role
  src/components/Dashboard/Dashboard.vue
  src/router/routes.ts
  src/util/constants.ts
Labels: enhancement
