Repository bcgov/fas-ui, pull requests merged in 2021-08, with the labels that each got.

#39 8344 Global Leader WIP PR
  src/App.vue
  src/components/RoutingSlip/CreateRoutingSlip.vue
  src/components/ViewRoutingSlip/PaymentInformation.vue
  src/components/common/ErrorAlertComponent.vue
  src/components/common/LoaderComponent.vue
  src/composables/RoutingSlip/useCreateRoutingSlip.ts
  src/composables/common/index.ts
  src/composables/common/useErrorAlert.ts
  src/composables/common/useLoader.ts
  src/locales/en.json
  src/services/routingSlip.services.ts
  src/shims-axios.d.ts
  src/store/index.ts
  src/store/modules/indicator.ts
  src/store/modules/routingSlip.ts
  src/util/constants.ts
  src/util/http-util.ts
  tests/unit/components/ViewRoutingSlip/transactionDataTable.spec.ts
  tests/unit/components/common/errorAlertComponent.spec.ts
  tests/unit/components/common/loaderComponent.spec.ts
Labels: WIP, enhancement

#41 Date Range Filter
  src/components/common/DateRangeFilter.vue
  src/composables/common/useDateRange.ts
  tests/unit/components/common/dateRangeFilter.spec.ts
Labels: enhancement, WIP

#42 Can directive
  src/components/Dashboard/Dashboard.vue
  src/components/ViewRoutingSlip/PaymentInformation.vue
  src/components/ViewRoutingSlip/RoutingSlipInfo.vue
  src/components/ViewRoutingSlip/RoutingSlipTransaction.vue
  tests/unit/components/Dashboard/dashboard.spec.ts
  tests/unit/components/ViewRoutingSlip/RoutingSlipInfo.spec.ts
  tests/unit/components/ViewRoutingSlip/paymentInformation.spec.ts
  tests/unit/components/ViewRoutingSlip/routingSlipTransaction.spec.ts
Labels: bug

#40 FAS: Search for a routing slip logic
  src/assets/scss/theme.scss
  src/components/Dashboard/Dashboard.vue
  src/components/Dashboard/Search.vue
  src/components/RoutingSlip/CreateRoutingSlip.vue
  src/components/ViewRoutingSlip/PaymentInformation.vue
  src/components/ViewRoutingSlip/RoutingSlipInfo.vue
  src/components/ViewRoutingSlip/RoutingSlipTransaction.vue
  src/components/common/DateRangeFilter.vue
  src/components/common/SearchColumnFilterComponent.vue
  src/components/common/StatusList.vue
  src/composables/Dashboard/useSearch.ts
  src/composables/common/index.ts
  src/composables/common/useDateRange.ts
  src/composables/common/useSearchColumnFilterComponent.ts
  src/locales/en.json
  src/models/Payment.ts
  src/models/RoutingSlip.ts
  src/services/routingSlip.services.ts
  src/store/modules/routingSlip.ts
  src/util/common-util.ts
  src/util/http-util.ts
  tests/unit/components/Dashboard/dashboard.spec.ts
  tests/unit/components/Dashboard/search.spec.ts
  tests/unit/components/ViewRoutingSlip/RoutingSlipInfo.spec.ts
  tests/unit/components/ViewRoutingSlip/paymentInformation.spec.ts
  tests/unit/components/ViewRoutingSlip/routingSlipTransaction.spec.ts
  tests/unit/components/common/dateRangeFilter.spec.ts
  tests/unit/components/common/searchColumnFilterComponent.spec.ts
  tests/unit/test-data/mock-search-headers.ts
Labels: WIP

#43 FAS: Search for a routing slip logic | Initiator field change
  src/components/Dashboard/Search.vue
Labels: enhancement

#44 FAS: Search for a routing slip logic | UX changed
  src/components/Dashboard/Dashboard.vue
  src/components/Dashboard/Search.vue
  src/components/ViewRoutingSlip/RoutingSlipInfo.vue
  src/components/common/DateRangeFilter.vue
  src/components/common/StatusList.vue
  src/composables/Dashboard/useSearch.ts
  src/composables/common/useDateRange.ts
  src/locales/en.json
  src/store/modules/routingSlip.ts
Labels: enhancement

#45 8528 - review routing slip
  src/assets/scss/base.scss
  src/components/ReviewRoutingSlip/ReviewRoutingSlip.vue
  src/components/ReviewRoutingSlip/ReviewRoutingSlipCashPayment.vue
  src/components/ReviewRoutingSlip/ReviewRoutingSlipChequePayment.vue
  src/components/ReviewRoutingSlip/ReviewRoutingSlipDetails.vue
  src/components/ReviewRoutingSlip/ReviewRoutingSlipPayment.vue
  src/components/ReviewRoutingSlip/index.ts
  src/components/RoutingSlip/CreateRoutingSlip.vue
  src/composables/ReviewRoutingSlip/index.ts
  src/composables/ReviewRoutingSlip/useReviewRoutingSlip.ts
  src/composables/RoutingSlip/useCreateRoutingSlip.ts
  src/composables/RoutingSlip/useCreateRoutingSlipPayment.ts
  src/store/modules/routingSlip.ts
  tests/unit/components/ReviewRoutingSlip/reviewRoutingSlip.spec.ts
  tests/unit/components/ReviewRoutingSlip/reviewRoutingSlipCashPayment.spec.ts
  tests/unit/components/ReviewRoutingSlip/reviewRoutingSlipChequePayment.spec.ts
  tests/unit/components/ReviewRoutingSlip/reviewRoutingSlipDetails.spec.ts
  tests/unit/components/ReviewRoutingSlip/reviewRoutingSlipPayment.spec.ts
  tests/unit/components/RoutingSlip/createRoutingSlipPayment.spec.ts
  tests/unit/components/routingSlip/createRoutingSlip.spec.ts
  tests/unit/test-data/mock-routing-slip.ts
Labels: enhancement

#46 FAS: Routing slip linkage(How its done) | designs
  src/assets/scss/overrides.scss
  src/assets/scss/theme.scss
  src/components/ViewRoutingSlip/LinkRoutingSlip.vue
  src/components/ViewRoutingSlip/LinkedRoutingSlipDetails.vue
  src/components/ViewRoutingSlip/RoutingSlipTransaction.vue
  src/components/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/useLinkRoutingSlip.ts
  src/locales/en.json
  src/views/ViewRoutingSlip.vue
  tests/unit/components/ViewRoutingSlip/routingSlipTransaction.spec.ts
Labels: enhancement

#49 Changes for new date format
  src/store/modules/routingSlip.ts
Labels: enhancement

#48 FAS: Routing slip linkage(How its done) | auto complete
  src/components/ViewRoutingSlip/LinkRoutingSlip.vue
  src/components/ViewRoutingSlip/RoutingSlipAutoComplete.vue
  src/components/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/useLinkRoutingSlip.ts
  src/composables/ViewRoutingSlip/useRoutingSlipAutoComplete.ts
  src/models/RoutingSlip.ts
  src/services/routingSlip.services.ts
  src/store/modules/routingSlip.ts
Labels: enhancement

#50 Feature/8528-payment
  src/components/RoutingSlip/CreateRoutingSlipCashPayment.vue
  src/components/RoutingSlip/CreateRoutingSlipChequePayment.vue
  src/components/ViewRoutingSlip/LinkedRoutingSlipsPaymentInfo.vue
  src/components/ViewRoutingSlip/PaymentInformation.vue
  src/components/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/useLinkedRoutingSlipsPaymentInfo.ts
  src/composables/ViewRoutingSlip/usePaymentInformation.ts
  src/composables/ViewRoutingSlip/useViewRoutingSlip.ts
  src/models/RoutingSlip.ts
  src/services/routingSlip.services.ts
  src/store/modules/routingSlip.ts
  tests/unit/components/ViewRoutingSlip/paymentInformation.spec.ts
Labels: enhancement, WIP

#51 FAS: Routing slip linkage(How its done) | link error and child
  src/components/ViewRoutingSlip/LinkRoutingSlip.vue
  src/components/ViewRoutingSlip/LinkedRoutingSlipDetails.vue
  src/composables/ViewRoutingSlip/useLinkRoutingSlip.ts
  src/composables/ViewRoutingSlip/useRoutingSlipAutoComplete.ts
  src/models/RoutingSlip.ts
  src/store/modules/routingSlip.ts
  src/util/common-util.ts
  src/util/constants.ts
Labels: enhancement

#52 Feature/8529- Linked RS Payment info changes
  src/components/ReviewRoutingSlip/ReviewRoutingSlip.vue
  src/components/ReviewRoutingSlip/ReviewRoutingSlipCashPayment.vue
  src/components/ReviewRoutingSlip/ReviewRoutingSlipChequePayment.vue
  src/components/ReviewRoutingSlip/ReviewRoutingSlipDetails.vue
  src/components/ReviewRoutingSlip/ReviewRoutingSlipPayment.vue
  src/components/ViewRoutingSlip/LinkRoutingSlip.vue
  src/components/ViewRoutingSlip/LinkedRoutingSlipDetails.vue
  src/components/ViewRoutingSlip/LinkedRoutingSlipsPaymentInfo.vue
  src/components/ViewRoutingSlip/PaymentInformation.vue
  src/components/ViewRoutingSlip/RoutingSlipAutoComplete.vue
  src/components/ViewRoutingSlip/RoutingSlipInfo.vue
  src/components/ViewRoutingSlip/index.ts
  src/components/common/ErrorAlertComponent.vue
  src/components/common/InterimLanding.vue
  src/composables/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/useLinkedRoutingSlipsPaymentInfo.ts
  src/composables/ViewRoutingSlip/usePaymentInformation.ts
  src/locales/en.json
  src/store/modules/routingSlip.ts
  tests/unit/components/ReviewRoutingSlip/reviewRoutingSlipDetails.spec.ts
  tests/unit/components/ViewRoutingSlip/linkRoutingSlip.spec.ts
  tests/unit/components/ViewRoutingSlip/linkedRoutingSlipDetails.spec.ts
  tests/unit/components/ViewRoutingSlip/paymentInformation.spec.ts
  tests/unit/components/ViewRoutingSlip/routingSlipAutoComplete.spec.ts
  tests/unit/components/common/interimLanding.spec.ts
  tests/unit/test-data/mock-routing-slip.ts
  tests/unit/views/auth/signinView.spec.ts
Labels: enhancement, WIP

#53 FAS: Search for a routing slip logic | debounce for search | zero fo…
  src/components/ViewRoutingSlip/LinkRoutingSlip.vue
  src/components/ViewRoutingSlip/LinkedRoutingSlipDetails.vue
  src/components/ViewRoutingSlip/RoutingSlipAutoComplete.vue
  src/composables/ViewRoutingSlip/useRoutingSlipAutoComplete.ts
  src/util/debounce.ts
Labels: enhancement

#54 FAS: Search for a routing slip logic | permission
  src/components/ViewRoutingSlip/LinkRoutingSlip.vue
Labels: enhancement

#60 Feature/8631 WIP
  src/components/ViewRoutingSlip/AddManualTransactionDetails.vue
  src/components/ViewRoutingSlip/RoutingSlipTransaction.vue
  src/components/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/useAddManualTransactionDetails.ts
  src/composables/ViewRoutingSlip/useRoutingSlipTransaction.ts
  src/models/RoutingSlip.ts
  src/util/common-util.ts
  src/util/constants.ts
  tests/unit/components/ViewRoutingSlip/addManualTransactionDetails.spec.ts
Labels: enhancement, WIP

#61 Add Manual Transactions - Scenario 3 (Staff Enters Filing Type)#8659
  src/components/ViewRoutingSlip/AddManualTransactionDetails.vue
  src/components/ViewRoutingSlip/FilingTypeAutoComplete.vue
  src/components/ViewRoutingSlip/RoutingSlipTransaction.vue
  src/composables/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/useAddManualTransactionDetails.ts
  src/composables/ViewRoutingSlip/useFilingTypeAutoComplete.ts
  src/models/Payment.ts
  src/services/routingSlip.services.ts
  src/store/modules/routingSlip.ts
  tests/unit/components/ViewRoutingSlip/addManualTransactionDetails.spec.ts
Labels: enhancement
