Repository bcgov/fas-ui, pull requests merged in 2021-09, with the labels that each got.

#62 Feature/8659 1
  src/components/ViewRoutingSlip/AddManualTransactionDetails.vue
  src/components/ViewRoutingSlip/FilingTypeAutoComplete.vue
  src/components/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/useAddManualTransactionDetails.ts
  src/composables/ViewRoutingSlip/useFilingTypeAutoComplete.ts
  tests/unit/components/ViewRoutingSlip/FilingTypeAutoComplete.spec.ts
  tests/unit/components/ViewRoutingSlip/addManualTransactionDetails.spec.ts
  tests/unit/test-data/mock-routing-slip.ts
Labels: enhancement

#63 Feature/8631- Update fees on Manual transaction records
  src/components/ViewRoutingSlip/AddManualTransactionDetails.vue
  src/components/ViewRoutingSlip/FilingTypeAutoComplete.vue
  src/components/ViewRoutingSlip/RoutingSlipTransaction.vue
  src/composables/ViewRoutingSlip/useAddManualTransactionDetails.ts
  src/composables/ViewRoutingSlip/useFilingTypeAutoComplete.ts
  src/composables/ViewRoutingSlip/useRoutingSlipTransaction.ts
  src/models/Payment.ts
  src/models/RoutingSlip.ts
  src/services/routingSlip.services.ts
  src/store/modules/routingSlip.ts
  src/util/common-util.ts
  tests/unit/components/ViewRoutingSlip/addManualTransactionDetails.spec.ts
  tests/unit/components/ViewRoutingSlip/routingSlipTransaction.spec.ts
  tests/unit/test-data/mock-routing-slip.ts
Labels: enhancement, WIP

#65 Add Manual Transactions - Scenario 8 (Staff clicks blue 'Add Transact…
  src/composables/ViewRoutingSlip/useAddManualTransactionDetails.ts
  src/composables/ViewRoutingSlip/useRoutingSlipTransaction.ts
  src/models/Payment.ts
  src/services/routingSlip.services.ts
  src/store/modules/routingSlip.ts
  tests/unit/components/ViewRoutingSlip/routingSlipTransaction.spec.ts
Labels: enhancement

#64 8631 - UI cosmetic changes
  src/assets/scss/theme.scss
  src/components/ViewRoutingSlip/AddManualTransactionDetails.vue
  src/components/ViewRoutingSlip/RoutingSlipTransaction.vue
  src/composables/ViewRoutingSlip/useAddManualTransactionDetails.ts
  src/composables/ViewRoutingSlip/useRoutingSlipTransaction.ts
  src/locales/en.json
  tests/unit/components/ViewRoutingSlip/routingSlipTransaction.spec.ts
Labels: enhancement

#66 bug fix - 8850
  src/components/ViewRoutingSlip/PaymentInformation.vue
  tests/unit/components/ViewRoutingSlip/paymentInformation.spec.ts
  tests/unit/test-data/mock-routing-slip.ts
Labels: bug

#67 8631 - UI - spacing
  src/components/ViewRoutingSlip/AddManualTransactionDetails.vue
Labels: enhancement

#68 token refresh
  src/main.ts
Labels: bug

#69 8631 - implement component level loading
  src/components/ViewRoutingSlip/RoutingSlipTransaction.vue
  src/composables/ViewRoutingSlip/useRoutingSlipAutoComplete.ts
  src/composables/ViewRoutingSlip/useRoutingSlipTransaction.ts
  src/composables/ViewRoutingSlip/useViewRoutingSlip.ts
  src/models/RoutingSlip.ts
  src/store/modules/routingSlip.ts
Labels: enhancement

#70 daily report
  src/composables/Dashboard/useDailyReport.ts
Labels: bug

#71 edit status hidden for linked RS and invoiced RS wont have linking option
  src/components/ViewRoutingSlip/LinkRoutingSlip.vue
  src/components/ViewRoutingSlip/RoutingSlipInfo.vue
  src/composables/ViewRoutingSlip/useLinkRoutingSlip.ts
  src/composables/ViewRoutingSlip/useRoutingSlipInfo.ts
  src/locales/en.json
  tests/unit/components/ViewRoutingSlip/linkRoutingSlip.spec.ts
Labels: enhancement

#73 fix manual transaction issues
  src/components/ViewRoutingSlip/AddManualTransactionDetails.vue
  src/components/ViewRoutingSlip/RoutingSlipTransaction.vue
  src/composables/ViewRoutingSlip/useAddManualTransactionDetails.ts
  src/composables/ViewRoutingSlip/useFilingTypeAutoComplete.ts
  src/composables/ViewRoutingSlip/useRoutingSlipTransaction.ts
  src/models/RoutingSlip.ts
  src/store/modules/routingSlip.ts
Labels: bug

#74 fix for 8860
  src/components/ViewRoutingSlip/AddManualTransactionDetails.vue
  src/composables/ViewRoutingSlip/useAddManualTransactionDetails.ts
  src/composables/ViewRoutingSlip/useRoutingSlipTransaction.ts
Labels: bug

#75 8860 bug fix
  src/composables/ViewRoutingSlip/useRoutingSlipTransaction.ts
Labels: bug

#86 Feature/8605 breadcrumb
  lib/lib.umd.min.js
  lib/lib.umd.min.js.map
  package-lock.json
  public/config/configuration.json
  src/components/Dashboard/Search.vue
  src/components/ViewRoutingSlip/LinkRoutingSlip.vue
  src/components/ViewRoutingSlip/LinkedRoutingSlipDetails.vue
  src/components/ViewRoutingSlip/PaymentInformation.vue
  src/components/common/BreadCrumb.vue
  src/composables/Dashboard/useSearch.ts
  src/composables/ViewRoutingSlip/index.ts
  src/composables/ViewRoutingSlip/useLinkedRoutingSlipDetails.ts
  src/composables/ViewRoutingSlip/usePaymentInformation.ts
  src/composables/common/index.ts
  src/composables/common/useBreadCrumb.ts
  src/lib-setup.js
  src/models/BreadcrumbItem.ts
  src/router/routes.ts
  src/util/common-util.ts
  src/util/config-helper.ts
  src/util/constants.ts
  src/views/Dashboard.vue
  src/views/ViewRoutingSlip.vue
  tests/unit/components/common/breadCrumb.spec.ts
Labels: enhancement

#87 8605 - FAS open event handler changes
  src/components/Dashboard/Search.vue
  src/composables/Dashboard/useSearch.ts
  tests/unit/components/Dashboard/search.spec.ts
Labels: bug

#90 Feature/8396
  src/assets/scss/overrides.scss
  src/assets/scss/search.scss
  src/components/Dashboard/Search.vue
  src/components/ViewRoutingSlip/LinkRoutingSlip.vue
  src/components/ViewRoutingSlip/LinkedRoutingSlipDetails.vue
  src/components/ViewRoutingSlip/PaymentInformation.vue
  src/components/ViewRoutingSlip/RoutingSlipInfo.vue
  src/components/ViewRoutingSlip/RoutingSlipTransaction.vue
  src/plugins/vuetify.ts
  src/util/common-util.ts
  src/views/ViewRoutingSlip.vue
  tests/unit/components/ViewRoutingSlip/RoutingSlipInfo.spec.ts
  tests/unit/components/ViewRoutingSlip/paymentInformation.spec.ts
  tests/unit/components/ViewRoutingSlip/routingSlipTransaction.spec.ts
  tests/unit/views/ViewRoutingSlip.spec.ts
Labels: enhancement, WIP

#89 Feature/8605-Breadcrumb-URI-update
  lib/lib.css
  lib/lib.umd.min.js
  lib/lib.umd.min.js.map
  src/composables/common/useBreadCrumb.ts
  tests/unit/components/common/breadCrumb.spec.ts
Labels: bug
